In [19]:
my_file = open("b.txt",'w')
a = int(input("first number"))
b = int(input("second number"))
c = int(input("third number"))
d = int(input("fourth number"))

my_file.write(str(a))
my_file.write(str(b))
my_file.write(str(c))
my_file.write(str(d))

my_file.close()

In [16]:
def mark_grade(a):
    if a>='75' :
        print('Grade A') 
    elif a<'75' and a>='50':
        print('Grade B')
    elif a<'50' and a>='25':
        print('Grade C')
    else :
        a>'0' and a<'25'
        print('Grade D')

def mark():
    a=input("What is your mark?")
    mark_grade(a)

mark()

Grade D


In [91]:
pip install numpy 

You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [104]:
#question 1

import numpy as np 

array1=np.arange(0,10,1)

print(array1)

[0 1 2 3 4 5 6 7 8 9]


In [105]:
#question 2

import numpy as np 

array2=np.arange(0,9,1)

print(array2)

array3x3=array2.reshape(3,3)

print(array3x3)

for x in array3x3 :
    if x >10 :
        print(bool)


[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [111]:
#question 3 

import numpy as np 

array2=np.arange(0,10,1)

print(array2)

for x in array2 :
    if (x %2) == 0:
        pass
    else :
        print(x)



[0 1 2 3 4 5 6 7 8 9]
1
3
5
7
9


In [115]:
#question 4 

import numpy as np 

array2=np.arange(0,10,1)

print(array2)

for x in array2 :
    if (x %2) == 0:
        pass
    else :
        print('i need code')
    # replace item with -1 

[0 1 2 3 4 5 6 7 8 9]
0
i need code
2
i need code
4
i need code
6
i need code
8
i need code


In [123]:
#question 5

import numpy as np 

array1d=[1,2,3,4,5,6,7,8,9,10]

array2d=np.reshape(array1d,(2,5))

print(array2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [46]:
#question 6

import numpy as np 

a=np.arange(1,5).reshape(2,2)
print(a)
b=np.arange(6,10).reshape(2,2)
print(b)

c=np.dot(a, b)
print(c)

sum=np.sum(c)
print(sum)



[[1 2]
 [3 4]]
[[6 7]
 [8 9]]
[[22 25]
 [50 57]]
154
